name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: NPM Pack
        working-directory: ./packages/ui
        run: |
          npm pack --pack-destination ../published
      - name: Build Site
        working-directory: ./
        env:
          NODE_ENV: production
        run: |
          npm install --include=dev --no-save
          npm run build
      - name: Deploy Site
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_DEPLOY_USERNAME }}
          server: ${{ secrets.FTP_DEPLOY_HOST }}
          port: ${{ secrets.FTP_DEPLOY_PORT }}
          local_path: "./apps/web/dist/*"
          remote_path: "./sites/kemet-ui-site/"
          sftp_only: true
          ssh_private_key: ${{ secrets.FTP_DEPLOY_PASSWORD }}
      - name: Deploy Docs
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_DEPLOY_USERNAME }}
          server: ${{ secrets.FTP_DEPLOY_HOST }}
          port: ${{ secrets.FTP_DEPLOY_PORT }}
          local_path: "./apps/docs/storybook-static/*"
          remote_path: "./sites/kemet-ui-site/docs/"
          sftp_only: true
          ssh_private_key: ${{ secrets.FTP_DEPLOY_PASSWORD }}
    